apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  INFLUXDB_DATABASE: aW5mbHV4ZGI= #influxdb
  INFLUXDB_USERNAME: YWRtaW4= #admin
  INFLUXDB_PASSWORD: YWRtaW4= #admin
  INFLUXDB_HOST: aW5mbHV4ZGI= #influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - envFrom:
        - secretRef:
              name: influxdb-secret       
        name: influxdb
        image: docker.io/influxdb:1.6.4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/influxdb"
            name: influxdb-pd   
      volumes:
          - name: influxdb-pd
            persistentVolumeClaim:
              claimName: influxdb-pvc