apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4= #admin
  MYSQL_USER: YWRtaW4= #admin
  MYSQL_PASSWORD: YWRtaW4= #admin
  MYSQL_DATABASE: d29yZHByZXNz #wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - envFrom:
        - secretRef:
              name: mysql-secret        
        name: mysql
        image: "mysql:5.6"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pd   
      volumes:
          - name: mysql-pd
            persistentVolumeClaim:
              claimName: mysql-pvc
 