apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  dbname: d29yZHByZXNz #wordpress
  dbuser: YWRtaW4= #admin
  dbpass: YWRtaW4= #admin
  dbrootpass: YWRtaW4= #admin

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "mysql:5.6"
          ports:
          - containerPort: 3306
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pd
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbrootpass
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbpass
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbname
      volumes:
          - name: mysql-pd
            persistentVolumeClaim:
              claimName: mysql-pvc
  selector:
    matchLabels:
      app: mysql

