apiVersion: v1
kind: Service
metadata:
  name: nginx-server
spec:
  type: NodePort
  ports:
  - name: http
    targetPort: 80
    port: 80
    nodePort: 30008
  - name: https
    targetPort: 443
    port: 443
    nodePort: 30009
  selector:
    app: myapp
    type: front-end

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
     app: myapp
     type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx_rbakker
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: "http-server"
          - containerPort: 433
            name: "https-server"

  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: front-end
