apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  - name: https
    targetPort: 443
    port: 443
  - name: ssh
    targetPort: 4000
    nodePort: 4000
    port: 4000
    protocol: TCP
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
     app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx_rbakker
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: "http-server"
          - containerPort: 433
            name: "https-server"
          - containerPort: 4000
            name: "ssh-server"
