apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WORDPRESS_DB_HOST: bXlzcWwtc2VydmljZQ== #mysql-service
  WORDPRESS_DB_USER: YWRtaW4= #admin
  WORDPRESS_DB_PASSWORD: YWRtaW4= #admin
  WORDPRESS_DB_NAME: d29yZHByZXNz #wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 5050
  selector:
    app: wordpress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - envFrom:
        - secretRef:
              name: wordpress-secret        
        name: wordpress
        image: wordpress:4.8-apache
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80